#!/bin/bash

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

menuStart
menuSeparator 'Online Help'
menuSeparator
menuItem 'Forum Help & Support' 'x-www-browser "http://crunchbang.org/forums/viewtopic.php?id=38737"'
menuItem 'Tips, Tricks & Scripts' 'x-www-browser "http://crunchbang.org/forums/viewforum.php?id=8"'
menuSubmenu 'DebianWWW' 'Debian'
menuItem 'Debian Documentation' 'x-www-browser "https://www.debian.org/doc/"'
menuItem 'Wiki' 'x-www-browser "https://wiki.debian.org/"'
menuItem 'Forum' 'x-www-browser "http://forums.debian.net/"'
menuItem 'Package Search' 'x-www-browser "https://www.debian.org/distrib/packages"'
menuItem 'Package Tracker' 'x-www-browser "https://tracker.debian.org/"'
menuItem 'Security Tracker' 'x-www-browser "https://security-tracker.debian.org/tracker/"'
menuSubmenuEnd
menuItem 'Arch wiki' 'x-www-browser "https://wiki.archlinux.org/index.php/Table_of_contents"'

menuSeparator

menuSubmenu 'OpenboxWWW' 'Openbox'
menuSubmenu 'ObWWW' 'Openbox website'
menuItem 'Openbox Homepage' 'x-www-browser "http://openbox.org/"'
menuItem 'Openbox Getting Started' 'x-www-browser "http://openbox.org/wiki/Help:Getting_started"'
menuItem 'Openbox Documentation' 'x-www-browser "http://openbox.org/wiki/Help:Contents"'
menuItem 'Openbox FAQs' 'x-www-browser "http://openbox.org/wiki/Help:FAQ"'
menuSubmenuEnd
menuItem 'ArchWiki Openbox guide' 'x-www-browser "http://wiki.archlinux.org/index.php/Openbox"'
menuItem 'Debian Wiki Openbox guide' 'x-www-browser "https://wiki.debian.org/Openbox"'
menuItem 'Urukramas Openbox Guide' 'x-www-browser "https://urukrama.wordpress.com/openbox-faq/"'
menuSubmenuEnd

menuSubmenu 'Tint2WWW' 'Tint2 panel'
menuItem 'Tint2 wiki: FAQ' 'x-www-browser "https://code.google.com/p/tint2/wiki/FAQ"'
menuItem 'Tint2 Documentation' 'x-www-browser "https://code.google.com/p/tint2/wiki/Configure"'
menuItem 'Tint2 forum thread' 'x-www-browser "http://crunchbang.org/forums/viewtopic.php?id=3232"'
menuSubmenuEnd

menuSubmenu 'ConkyWWW' 'Conky'
menuItem 'Conky Configuration settings' 'x-www-browser "http://conky.sourceforge.net/config_settings.html"'
menuItem 'Conky Variables' 'x-www-browser "http://conky.sourceforge.net/variables.html"'
menuItem 'Conky Archive' 'x-www-browser "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
menuSubmenuEnd
menuSeparator

menuSubmenu 'ThemesWWW' 'Theme Resources'
menuItem 'Box-Look.org' 'x-www-browser "http://www.box-look.org"'
menuItem 'gnome-look.org' 'x-www-browser "http://gnome-look.org/"'
menuItem 'DeviantArt' 'x-www-browser "http://www.deviantart.com/browse/all/"'
menuSubmenuEnd
menuSeparator
menuSeparator "man pages"
menuItem "Conky" "x-terminal-emulator -e man conky"
menuItem "Compositor" "x-terminal-emulator -e man compton"
menuItem "dmenu" "x-terminal-emulator -e man dmenu"
menuItem "gmrun" "x-terminal-emulator -e man gmrun"
menuItem "Tint2" "x-terminal-emulator -e man tint2"
menuItem "xrandr" "x-terminal-emulator -e man xrandr"

menuEnd
