#!/bin/bash
#
# bl-help-pipemenu
# Prepared for BunsenLabs Linux by damo <damo@bunsenlabs.org> March 2015

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

menuStart
menuSeparator 'Online Help'
menuSeparator
menuItem 'Forum Basic Help & Support' 'x-www-browser "https://forums.bunsenlabs.org/viewforum.php?id=2"'
menuItem 'Scripts, Tutorials & Tips' 'x-www-browser "https://forums.bunsenlabs.org/viewforum.php?id=9"'
menuSubmenu 'DebianWWW' 'Debian'
menuItem 'Debian Documentation' 'x-www-browser "https://www.debian.org/doc/"'
menuItem 'Debian Handbook' 'x-www-browser "https://debian-handbook.info/browse/jessie/"'
menuItem 'Debian Reference' 'x-www-browser "https://www.debian.org/doc/manuals/debian-reference/"'
menuItem 'Wiki' 'x-www-browser "https://wiki.debian.org/"'
menuItem 'Forum' 'x-www-browser "http://forums.debian.net/"'
menuItem 'Package Search' 'x-www-browser "https://www.debian.org/distrib/packages"'
menuItem 'Package Tracker' 'x-www-browser "https://tracker.debian.org/"'
menuItem 'Security Tracker' 'x-www-browser "https://security-tracker.debian.org/tracker/"'
menuSubmenuEnd
menuItem 'Arch Wiki' 'x-www-browser "https://wiki.archlinux.org/index.php/Table_of_contents"'

menuSeparator

menuSubmenu 'OpenboxWWW' 'Openbox'
menuSubmenu 'ObWWW' 'Openbox Website'
menuItem 'Openbox Homepage' 'x-www-browser "http://openbox.org/"'
menuItem 'Openbox Getting Started' 'x-www-browser "http://openbox.org/wiki/Help:Getting_started"'
menuItem 'Openbox Documentation' 'x-www-browser "http://openbox.org/wiki/Help:Contents"'
menuItem 'Openbox FAQs' 'x-www-browser "http://openbox.org/wiki/Help:FAQ"'
menuSubmenuEnd
menuItem 'ArchWiki Openbox Guide' 'x-www-browser "http://wiki.archlinux.org/index.php/Openbox"'
menuItem 'Debian Wiki Openbox Guide' 'x-www-browser "https://wiki.debian.org/Openbox"'
menuItem 'Urukramas Openbox Guide' 'x-www-browser "https://urukrama.wordpress.com/openbox-faq/"'
menuSubmenuEnd

menuSubmenu 'Tint2WWW' 'Tint2'
menuItem 'Tint2 Wiki: FAQ' 'x-www-browser "https://gitlab.com/o9000/tint2/wikis/FAQ"'
menuItem 'Tint2 Wiki: Configuration' 'x-www-browser "https://gitlab.com/o9000/tint2/wikis/Configure"'
menuItem 'Tint2 Forum Thread' 'x-www-browser "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
menuItem 'Tint2 man page' 'x-terminal-emulator -T "Tint2 man page" -e man tint2'
menuSubmenuEnd

menuSubmenu 'ConkyWWW' 'Conky'
menuItem 'Conky Configuration Settings' 'x-www-browser "http://conky.sourceforge.net/config_settings.html"'
menuItem 'Conky Variables' 'x-www-browser "http://conky.sourceforge.net/variables.html"'
menuItem 'Conky Archive' 'x-www-browser "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
menuItem 'Conky man pages' 'x-terminal-emulator -T "Conky man page" -e man conky'
menuSubmenuEnd
menuSeparator

menuSubmenu 'ThemesWWW' 'Theme Resources'
menuItem 'Box-Look.org' 'x-www-browser "http://www.box-look.org"'
menuItem 'gnome-look.org' 'x-www-browser "http://gnome-look.org/"'
menuItem 'DeviantArt' 'x-www-browser "http://www.deviantart.com/browse/all/"'
menuSubmenuEnd
menuSeparator
menuSeparator 'man pages'
menuItem 'Compositor' 'x-terminal-emulator -T "Compositor man page" -e man compton'
menuItem 'dmenu' 'x-terminal-emulator -T "dmenu man page" -e man dmenu'
menuItem 'gmrun' 'x-terminal-emulator -T "gmrun man page" -e man gmrun'
menuItem 'xrandr' 'x-terminal-emulator -T "xrandr man page" -e man xrandr'


menuEnd
