#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for displaying keybinds.
# bl-kb.py is used to parse rc.xml and send the output to a textfile
#
# Written by <damo> for BunsenLabs Linux,  April 2015
# ---------------------------------------------------------------------
#
# NB The keybinds in the menu are clickable, except for the Openbox
# commands, which just exit the menu
#-----------------------------------------------------------------------
BL_COMMON_LIBDIR="/usr/lib/bunsen/bunsen-common"
KBSCRIPT="bl-kb.py"
RCPATH=".config/openbox/rc.xml"
KBTEXT=".config/openbox/kbinds.txt"

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
	exit 1
fi

if ! [ -e "$KBTEXT" ];then # write keybinds to textfile, if it doesn't exist
	# test if bl-kb.py exists in path
	if type "$KBSCRIPT" &> /dev/null;then
		# run script to write kbinds.txt, suppress terminal output
		"$KBSCRIPT" > /dev/null
	else
		echo $"ERROR: bl-kb.py not found" >&2
		exit 1
	fi
fi

if [[ $1 = '--rcedit' ]];then # "Backup & Edit rc.xml" is chosen in menu
	# backup rc.xml first
	NOW=$(date +"%Y%m%d-%H%M")
	RCBKP="$RCPATH.$NOW"
	cp "$RCPATH" "$RCBKP"
	xdg-open "$RCPATH"		# open rc.xml in default editor

fi

# pipemenu
menuStart
menuItem "Backup and Edit rc.xml" "bl-kb-pipemenu --rcedit"
menuItem "Refesh keybinds list" "bl-kb.py" # use if rc.xml has been edited
menuSeparator
menuSeparator "Openbox window commands"
while read -r a b c;do		# write out Openbox commands (not clickable)
	if [[ "$a" = "o" ]];then
		curItem=$(printf "%-20s %s" "$b" "$c")
		menuItem "$curItem" "echo >/dev/null 2>&1"
	fi
done < "$KBTEXT"

menuSeparator
menuSeparator "'Run' commands"
while read -r a b c;do		# write out 'Run' commands (clickable)
	if [[ "$a" = "x" ]];then
		curItem=$(printf "%-20s %s" "$b" "$c")
		menuItem "$curItem" "$c"
	fi
done < "$KBTEXT"

menuEnd

exit 0
