#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for use with LibreOffice and Bunsen Labs Linux.
# Originally written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

if [[ $1 = '--install' ]]; then
    x-terminal-emulator -T 'Install LibreOffice' -e "$0" --install-lo

elif [[ $1 = '--install-lo' ]]; then
    promptInstall 'LIBREOFFICE' 'LibreOffice' 'bunsen-meta-libreoffice'

else
    # Pipemenu
    menuStart

    tools=('writer' 'calc' 'impress' 'draw' 'base')

    for curTool in "${tools[@]}"; do
        if type "lo$curTool" &> /dev/null; then
            INSTALLED=true
            menuItem "${curTool^}" "lo$curTool"
        fi
    done

    [[ ! $INSTALLED ]] &&
        menuItem 'Install LibreOffice' "$0 --install"

    menuEnd
fi
exit 0
