#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for use with LibreOffice and Bunsen Labs Linux.
# Originally written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
# ---------------------------------------------------------------------

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

LO_APPS=('libreoffice-writer' 'libreoffice-calc' 'libreoffice-impress' 'libreoffice-draw' 'libreoffice-base')

declare -A AppName AppStatus AppCmd
for curApp in "${LO_APPS[@]}"; do
    name="${curApp#libreoffice-}"
    AppName[$curApp]="LibreOffice ${name^}"
    AppCmd[$curApp]=lo$name
    type "${AppCmd[$curApp]}" >/dev/null 2>&1 && AppStatus[$curApp]=installed
done

appExists() {
    for curApp in "${LO_APPS[@]}"; do # if $packageName exists in LO_APPS array
        [[ $curApp = "$1" ]] &&
            return 0
    done
    say "Unable to install $1. There is no such application that I know of." 1 >&2
    say "You can try one of these: ${LO_APPS[*]}" 2 >&2
    return 1
}

if [[ $1 && ! $1 = --install-* ]]; then
    packageName=${1#--}
    x-terminal-emulator -T "Install ${AppName[$packageName]}" -e "$0" "--install-$packageName"

elif [[ $1 = --install-* ]]; then
    packageName=${1#--install-}
    if [[ $packageName = bunsen-meta-libreoffice ]]
    then
        promptInstall "LIBREOFFICE FULL SUITE" "the Full LibreOffice Suite" "$packageName"
    else
        appExists "$packageName" || exit 1
        promptInstall --no-install-recommends "${AppName[$packageName]^^}" "${AppName[$packageName]} (without recommends)" "$packageName"
    fi

else
    # Pipemenu
    menuStart

    for curApp in "${LO_APPS[@]}"; do
        if [[ ${AppStatus[$curApp]} = installed ]]; then
            menuItem "${AppName[$curApp]}" "${AppCmd[$curApp]}"
        fi
    done
    submenu_started=false
    for curApp in "${LO_APPS[@]}"; do
        if ! [[ ${AppStatus[$curApp]} = installed ]]; then
            $submenu_started || menuSubmenu "lo-apps-install-submenu" "Install"
            submenu_started=true
            menuItem "Install ${AppName[$curApp]}" "$0 --$curApp"
        fi
    done
    if ! dpkg -s libreoffice >/dev/null 2>&1
    then
        $submenu_started || menuSubmenu "lo-apps-install-submenu" "Install"
        submenu_started=true
        menuItem "Install Full LibreOffice Suite" "$0 --bunsen-meta-libreoffice"
    fi
    $submenu_started && menuSubmenuEnd

    menuEnd
fi
exit 0
