#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for Multimedia applications.
#
# Originally written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
#
# Modified by <damo> for BunsenLabs Linux, March 2015
# ---------------------------------------------------------------------
# Applications to display in the editors and utilities sections can be
# changed by editing the "TOOLS" arrays in:
#           $BL_INCLUDE/bl-MMeditors-pipemenu
#           $BL_INCLUDE/bl-MMutils-pipemenu
# ---------------------------------------------------------------------


BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'
BL_INCLUDE='/usr/bin'   # used for editor and utility pipemenus

# In order to add another APP, add the package name to this array:
APPS=( 'vlc' 'deadbeef' 'mpv' 'audacious' 'smplayer' )

# If the package needs additional configuration before installation
# create a function called setupappName, it will be called automatically.


if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
	exit 1
fi

appExists() {
	for curApp in "${APPS[@]}"; do # if $packageName exists in APPS array
		[[ $curApp = "$1" ]] &&
			return 0
	done
	say "Unable to install $1. There is no such application that I know of." 1 >&2
	say "You can try one of these: ${APPS[*]}" 2 >&2
	return 1
}


if [[ $1 && ! $1 = --install-* ]]; then
	packageName=${1#--}
	read -ra words <<< "${packageName//-/ }"
	x-terminal-emulator --title "Install ${words[*]^}" -e "$0" "--install-$packageName"

elif [[ $1 = --install-* ]]; then
	packageName=${1#--install-}
	appExists "$packageName" || exit 1
	appName=${packageName//-/ }
	read -ra words <<< "$appName"
	appName=${words[*]^}
	appNameUpper=${appName^^}

	setupFunctionName="setup${appName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
		promptInstall --setup "$setupFunctionName" "${appNameUpper% APP} APP" "$appName" "$packageName"
	else
		promptInstall "${appNameUpper% APP} APP" "$appName" "$packageName"
	fi

else # pipemenu
	menuStart
	for curApp in "${APPS[@]}"; do
		read -ra words <<< "${curApp//-/ }"
		echo "$curApp"
		curAppName=${words[*]^}
		if type "$curApp" &> /dev/null; then
			# change name of smplayer (gui frontend for mplayer)
			if [[ "$curApp" = "smplayer" ]];then
				menuItem "Gnome mplayer" "$curApp"
				curAppName=${words[*]^}
			elif [[ "$curApp" = "mpv" ]];then # set mpv to start with gui window
				menuItem "$curAppName" "$curApp --force-window --idle"
			else
				menuItem "$curAppName" "$curApp"
			fi
		else
			if [[ "$curAppName" == "Smplayer" ]]; then
				menuItem "Install Gnome mplayer" "$0 --$curApp"
			else
				menuItem "Install $curAppName" "$0 --$curApp"
			fi
		fi
	done
    menuSeparator
	menuSeparator 'Editors'
    # get editors pipemenu
	if ! type "$BL_INCLUDE/bl-MMeditors-pipemenu" &> /dev/null; then
		echo $"Error: Failed to locate pipemenu in $BL_INCLUDE" >&2
		exit 1
	else
		echo $($BL_INCLUDE/bl-MMeditors-pipemenu)
	fi
    menuSeparator
	menuSeparator 'Utilities'
    # get utilities pipemenu
	if ! type "$BL_INCLUDE/bl-MMutils-pipemenu" &> /dev/null; then
		echo $"Error: Failed to locate pipemenu in $BL_INCLUDE" >&2
		exit 1
	else
		echo $($BL_INCLUDE/bl-MMutils-pipemenu)
	fi
	menuEnd
fi
exit 0
