#!/bin/bash
# ---------------------------------------------------------------------
# An Openbox pipemenu for Multimedia editors
# It is used by bl-multimedia-pipemenu to populate the MM editors menu
#
# Originally written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
#
# Modified by <damo> for BunsenLabs Linux, March 2015
# ---------------------------------------------------------------------

BL_COMMON_LIBDIR='/usr/lib/bunsen/bunsen-common'

# In order to add another TOOL, add the package name to this array:
TOOLS=('mhwaveedit' 'audacity' 'openshot')

# If the package needs additional configuration before installation
# create a function called setuptoolName, it will be called automatically.


if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
	echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
	exit 1
fi

toolExists() {
	for curTool in "${TOOLS[@]}"; do # if $packageName exists in TOOLS array
		[[ $curTool = "$1" ]] &&
			return 0
	done
	say "Unable to install $1. There is no such application that I know of." 1 >&2
	say "You can try one of these: ${TOOLS[*]}" 2 >&2
	return 1
}


if [[ $1 && ! $1 = --install-* ]]; then
	packageName=${1#--}
	read -ra words <<< "${packageName//-/ }"
	x-terminal-emulator -T "Install ${words[*]^}" -e "$0" "--install-$packageName"

elif [[ $1 = --install-* ]]; then
	packageName=${1#--install-}
	toolExists "$packageName" || exit 1
	toolName=${packageName//-/ }
	read -ra words <<< "$toolName"
	toolName=${words[*]^}
	toolNameUpper=${toolName^^}

	setupFunctionName="setup${toolName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupBlender'
	if [[ $(type -t "$setupFunctionName") = 'function' ]]; then
		promptInstall --setup "$setupFunctionName" "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
	else
		promptInstall "${toolNameUpper% TOOL} TOOL" "$toolName" "$packageName"
	fi

else # output for bl-multimedia-pipemenu
	for curTool in "${TOOLS[@]}"; do
		read -ra words <<< "${curTool//-/ }"
		curToolName=${words[*]^}
		if type "$curTool" &> /dev/null; then
			menuItem "$curToolName" "$curTool"
		else
			menuItem "Install $curToolName" "$0 --$curTool"
		fi
	done

fi
exit 0
